### ISSUE TITLE
Use findOne for other parameters than id?

### ISSUE THREAD

**Issue by iparker** [nuxt-community/strapi-module#101]
Hello,

is there a way to call the findOne-method with other parameters than the id, for example with a slug?

In module-documentation https://strapi.nuxtjs.org/strapi#findoneentity-id is the findOne just with a fixed id.

In strapi-documentation is the findOne-call also with an object possible (https://strapi.io/documentation/developer-docs/latest/concepts/queries.html#api-reference).

That would be a great feature. 

Thanks for some help with this!

Best regards,

Timo

**Comment by iparker** [comment]
Thanks for your reply!

I tried the following code in controllers/article.js:

```
const { sanitizeEntity } = require('strapi-utils');
module.exports = {
  async findOne (ctx) {
    const { slug } = ctx.params;

    const entity = await strapi.services.article.findOne({ slug });
    return sanitizeEntity(entity, { model: strapi.models.article });
  },
};
```

But with this I get always a different result when I call this route for a slug, for example articles/my-slug.

I'm also wondering why it still "works" with an id. For the route articles/1 I also get differect articles for each request.

I don't know what's the mistake and how to solve this behaviour.

**Comment by NooBiToo** [comment]
> Спасибо за ответ!
> 
> Я попробовал следующий код в controllers / article.js:
> 
> ```
> const { sanitizeEntity } = require('strapi-utils');
> module.exports = {
>   async findOne (ctx) {
>     const { slug } = ctx.params;
> 
>     const entity = await strapi.services.article.findOne({ slug });
>     return sanitizeEntity(entity, { model: strapi.models.article });
>   },
> };
> ```
> 
> Но при этом я всегда получаю другой результат, когда вызываю этот маршрут для слага, например, article / my-slug.
> 
> Еще мне интересно, почему он до сих пор "работает" с id. Для статей маршрута / 1 я также получаю разные статьи по каждому запросу.
> 
> Я не знаю, в чем ошибка и как исправить такое поведение.

Hey! I made such a decision for myself, I hope it helps you
sorry for my bad english

1) Add Route

```
  {
    "method": "GET",
    "path": "/article/:url",
    "handler": "articles.one",
    "config": {
      "policies": []
    }
  },
```
_____________________________
2) Add Service

  module.exports = {
    /**
    * Promise to fetch record
    *
    * @return {Promise}
    */

    one(params) {
      return strapi.query('articles').findOne(params);
      // return params;
    },
  };
_____________________________
3) Add Controller

```
  'use strict';
  const { parseMultipartData, sanitizeEntity } = require('strapi-utils');

  module.exports = {
    /**
    * Retrieve a record.
    *
    * @return {Object}
    */

    one: async ctx => {
      const { url } = ctx.params;
      const entity = await strapi.services.articles.one({ url });
      // return sanitizeEntity(entity, { model: strapi.models.articles });
      return entity;
    },
  };
```
_____________________________
4) (optional) Add GraphQL
  4.1) create file schema.graphql.js in folder config

```
    const { sanitizeEntity } = require('strapi-utils');

    module.exports = {
      query: `
        articleByUrl(url: String name: String): Articles
      `,
      resolver: {
        Query: {
          articleByUrl: {
            resolverOf: 'Articles.one',
            async resolver(_, { url }) {
              const entity = await strapi.services.articles.one({ url });
              return sanitizeEntity(entity, { model: strapi.models.articles });
            },
          },
        },
      },
    };
```

Example query
```
    query ($url: String = "url") {
      articleByUrl(url: $url) {
        id
        title
        content
        created_at
        image {
          url
        }
      }
    }
```

**Comment by iparker** [comment]
@benjamincanac Thanks for this hint. I changed the route to:

```
{
      "method": "GET",
      "path": "/articles/:slug",
      "handler": "article.findOne",
      "config": {
        "policies": []
      }
```

And with the following controller it works:

```
  async findOne (ctx) {
    const { slug } = ctx.params;

    const entity = await strapi.services.article.findOne({ slug });
    return sanitizeEntity(entity, { model: strapi.models.article });
  },
```

Thanks for your help!

**Comment by iparker** [comment]
One more short question to this: What is the right naming schema.

I want adapt this code to another model named article-category.

The folder name with the json is article-category. 

I tried the following code to change the findOne:

```
const { sanitizeEntity } = require('strapi-utils');

module.exports = {

  async findOne (ctx) {
    const { slug } = ctx.params;

    const entity = await strapi.services.article-category.findOne({ slug });
    return sanitizeEntity(entity, { model: strapi.models.article-category });
  },
};
```
I tried different naming variants of the service but nothing worked for me.

Hope you can help me with this!

Best regards,

Timo
