### ISSUE TITLE
Sending email from Nuxt site using the Strapi email plugin

### ISSUE THREAD

**Issue by vogordin** [nuxt-community/strapi-module#102]
Is it possible to?

I just need to send data from the contact form on the site to the administrative email. I don't want to create a separate service for this, especially since Strapy has his own solution. But I don't understand how to use it directly from the frontend.

As far as I can see, we do not have access to $strapi.plugins['email']...  I can only create a collection like Messages. Then submit the new post to the collection from the contact form. And on the Strapi side create a trigger (idk how) for sending a letter when a new post created in this collection?

Am I thinking right? Maybe there is some simpler solution or a ready-made example of such an approach?

**Comment by fmctaggart** [comment]
You could just [add a new route](https://strapi.io/documentation/developer-docs/latest/concepts/routing.html) to an existing collection. Then link this route to a [new controller](https://strapi.io/documentation/developer-docs/latest/concepts/controllers.html), which you [call your email service from](https://strapi.io/documentation/developer-docs/latest/plugins/email.html). There is no need to add a whole collection unless you plan on storing these emails in your database.

**Comment by benjamincanac** [comment]
@vogordin The Email plugin adds a `send` route which you can use directly from your frontend:

```js
await this.$strapi.$http.$post('/email', { to: '', subject: ``, text: `` })
```

Don't forget to authorize this route in your Strapi Admin.
