### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by nttdataxd** [nuxt-community/strapi-module#106]
### Version
@nuxtjs/strapi:  v0.3.0
nuxt: 2.14.12

### Reproduction Link
When following the example EXACTLY as shown here with @nuxtjs/strapi tutorial here:
https://strapi.io/documentation/developer-docs/latest/getting-started/nuxt-js.html

The example worked perfectly with Axios and Fetch.

### Steps to reproduce
Follow the above tutorial in a brand new Nuxt and Strapi install.

### What is Expected?
Return the results from the rest API endpoint for the restaurants collection

### What is actually happening?
Returns an error:   "TypeError: Cannot read property 'find' of undefined"

**Comment by nttdataxd** [comment]
> Hi @nttdataxd, where did you put the http call `await this.$strapi.find('restaurants')`?
> 
> `this.$strapi` can be used in `fetch`, however when using `asyncData` you don't have access to `this` (see https://nuxtjs.org/docs/2.x/features/data-fetching#async-data), you have to do it like this:
> 
> ```js
> async asyncData ({ $strapi }) {
>   const restaurants = await $strapi.find('restaurants')
> 
>   return {
>     restaurants
>   }
> }
> ```
> 
> You can check out this section on the documentation to have more informations https://strapi.nuxtjs.org/strapi

I used the code from the site:

`export default {
  name: 'App',
  data () {
    return {
      restaurants: [],
      error: null
    }
  },
  async mounted () {
    try {
      this.restaurants = await this.$strapi.$restaurants.find()
    } catch (error) {
      this.error = error
    }
  }
}`

**Comment by Milou6** [comment]
To anyone having the same issue, I managed to solve this by using `fetch()` instead of `async mounted()`, using the example from the Nuxt docs linked by @benjamincanac ([https://nuxtjs.org/docs/2.x/features/data-fetching#async-data](https://nuxtjs.org/docs/2.x/features/data-fetching#async-data)).

My code that kept throwing **TypeError: Cannot read property 'find' of undefined**


```javascript
  async mounted() {  
    try {
      this.articles = await this.$strapi.$articles.find()
    } catch (error) {
      this.error = error
    }
  },
```

Changing to using `fetch()` (with my Strapi backend HTTP address for my blog articles), and now it works:

```javascript
  async fetch() {
    this.articles = await fetch('http://localhost:1337/articles').then((res) =>
      res.json()
    )
  },
```
