### ISSUE TITLE
Login using OAuth Providers

### ISSUE THREAD

**Issue by rylax** [nuxt-community/strapi-module#107]
### Is your feature request related to a problem? Please describe.
Would be great to have the possibility to login with OAuth Providers such as Google or Github and then automatically store the JWT for future requests.

**Comment by AdrianoCahete** [comment]
I was searching this right now to connect to Auth0 and, since there's nothing on Docs, I was searching here.

+1 for the improvement.

**Comment by benjamincanac** [comment]
Closing this as it has been implemented in `v1.0.0` version of the module for nuxt 3 with [getProviderAuthenticationUrl](https://strapi.nuxtjs.org/usage#getproviderauthenticationurl) and [authenticateProvider](https://strapi.nuxtjs.org/usage#authenticateprovider) methods.
