### ISSUE TITLE
Which is the best stage to fetch data in a page? 

### ISSUE THREAD

**Issue by brunogonzales** [nuxt-community/strapi-module#115]

**Comment by brunogonzales** [comment]
If I want to fetch data using the strapi plugin to populate content in a page I should always do it on the mounted hook?

**Comment by benjamincanac** [comment]
@brunogonzales You can either do it in `asyncData` or `fetch` depending on your use-case. See https://nuxtjs.org/docs/2.x/features/data-fetching/
