### ISSUE TITLE
Middlewares showing different things

### ISSUE THREAD

**Issue by AdrianoCahete** [nuxt-community/strapi-module#117]
Hi, I have a project with Auth0 as an auth provider. The redirect/callback works fine, the `jwt` is added as a cookie and everything. On the Login page, I can display the `$strapi.user` info.

The problem happens when I need to use the middleware:
I have two middlwwares:
- One to tell me when the user is logged in, to show some secret pages (`auth.js`)
- Another to tell me when the user is not logged, to redirect to login  (`authenticated.js`)

![image](https://user-images.githubusercontent.com/37474/111006983-8ec65000-836c-11eb-9ac4-2ce2f411378c.png)

I'm doing this because I have some public pages, like `forgot-password` and `register`, for example, that I don't want that someone that is already logged in can see.

The problem is:
After I pass the login flow, starts a war between that two middleware:
![image](https://user-images.githubusercontent.com/37474/111007141-e664bb80-836c-11eb-8239-df622b3e1496.png)

I know that the `$strapi` exists (and is not null) because I can see all the info on the login page. But what's happening with one telling me that the `$strapi` exists and another telling me otherwise?

Just to understand: the local (username/password) flow works flawlessly.

**Comment by NooBiToo** [comment]
> Hi, I have a project with Auth0 as an auth provider. The redirect/callback works fine, the `jwt` is added as a cookie and everything. On the Login page, I can display the `$strapi.user` info.
> 
> The problem happens when I need to use the middleware:
> I have two middlwwares:
> 
> * One to tell me when the user is logged in, to show some secret pages (`auth.js`)
> * Another to tell me when the user is not logged, to redirect to login  (`authenticated.js`)
> 
> ![image](https://user-images.githubusercontent.com/37474/111006983-8ec65000-836c-11eb-9ac4-2ce2f411378c.png)
> 
> I'm doing this because I have some public pages, like `forgot-password` and `register`, for example, that I don't want that someone that is already logged in can see.
> 
> The problem is:
> After I pass the login flow, starts a war between that two middleware:
> ![image](https://user-images.githubusercontent.com/37474/111007141-e664bb80-836c-11eb-8239-df622b3e1496.png)
> 
> I know that the `$strapi` exists (and is not null) because I can see all the info on the login page. But what's happening with one telling me that the `$strapi` exists and another telling me otherwise?
> 
> Just to understand: the local (username/password) flow works flawlessly.

but you have to use $strapi.user
```
export default function ({ redirect, $strapi }) {
  if (!$strapi.user) {
    return redirect("/login");
  }
}
```

**Comment by benjamincanac** [comment]
Closing this as there was no answer from author and @NooBiToo solution seems to be right.
