### ISSUE TITLE
Access user object via Vuex like nuxt/auth?

### ISSUE THREAD

**Issue by greenermoose** [nuxt-community/strapi-module#119]
First, thanks to everyone who has worked on this module. It's working well for me as I learn nuxt and strapi.

I started with nuxt and nuxt/auth and am now moving to nuxt with nuxt/strapi.

With nuxt/auth, the user object contains details about the authenticated user such as name. You can access it using either $auth or Vuex, i.e. in vuex actions you can access state.auth.user.

To make this possible with nuxt/strapi, I've created my own vuex auth named space and set state.auth.user manually via this pair of calls whenever I login:

        await this.$strapi.login({ identifier, password })
        this.$store.dispatch( { type: 'auth/login', user: this.$strapi.user } )

My store/auth.js file is

  // Vuex store for authentication

  export const state = () => ({
    user: false
  })

  export const mutations = {
    login (state, { user }) {
      state.user = user
    },
    logout (state, payload) {
      state.user = false
    }
  }

  export const actions = {
    login ({ commit, state}, { user }) {
      commit({ type: 'login', user })
    },
    logout ({commit, state}, payload) {
      commit({ type: 'logout', payload })
    }
  }

I wonder if I'm missing something (if the nuxt/strapi module does provide access to the authenticated user object via Vuex and I'm just missing it) or whether this functionality could be added to strapi so that $strapi.login() would automatically update $store.auth.user and I wouldn't need to do it in my code separately.

Sorry I'm just learning and am having a hard time fully understanding this repo's code. But I'd be willing to help work on this if someone could show me how to get started! Thanks, -Fred

**Comment by greenermoose** [comment]
Hi Atinux, thank you very much for getting back to me so quickly. I think I didn't explain clearly.

I wrote my initial code using nuxt/auth for authentication which allowed me to use Vuex for all of my authentication reactivity. I followed some other tutorials which did this in store/index.js:

export const getters = {
  isAuthenticated(state) {
    return state.auth.loggedIn
  },
  loggedInUser(state) {
    return state.auth.user
  }
}

When I switched to nuxt/strapi for authentication, I thought I could just update these getters, but I couldn't figure out how to access this.$strapi from Vuex. I'm probably missing something.

Since nuxt/auth provides both ways to get to the user object (through `this.$auth.user` or `this.$store.state.auth.user`, see https://auth.nuxtjs.org/api/auth), I thought this might be possible with nuxt/strapi, too.  If nothing else, it would help make it easier to go back and forth from nuxt/auth and nuxt/strapi.

Thanks again for the quick response.

**Comment by NooBiToo** [comment]
> Hi Atinux, thank you very much for getting back to me so quickly. I think I didn't explain clearly.
> 
> I wrote my initial code using nuxt/auth for authentication which allowed me to use Vuex for all of my authentication reactivity. I followed some other tutorials which did this in store/index.js:
> 
> export const getters = {
> isAuthenticated(state) {
> return state.auth.loggedIn
> },
> loggedInUser(state) {
> return state.auth.user
> }
> }
> 
> When I switched to nuxt/strapi for authentication, I thought I could just update these getters, but I couldn't figure out how to access this.$strapi from Vuex. I'm probably missing something.
> 
> Since nuxt/auth provides both ways to get to the user object (through `this.$auth.user` or `this.$store.state.auth.user`, see https://auth.nuxtjs.org/api/auth), I thought this might be possible with nuxt/strapi, too. If nothing else, it would help make it easier to go back and forth from nuxt/auth and nuxt/strapi.
> 
> Thanks again for the quick response.

commit("SET_USER", this.$strapi.user); its working

**Comment by greenermoose** [comment]
> > [...] I couldn't figure out how to access this.$strapi from Vuex. I'm probably missing something.
> 
> commit("SET_USER", this.$strapi.user); its working

Thank you @NooBiToo !

**Comment by greenermoose** [comment]
> We are planning to have `@nuxt/session` that will be shared for modules such as Strapi and @nuxtjs/auth to have a unified solution for authenticated user 😊

Perfect! Nuxt is already really great. Having a standard for authenticated user sessions will make it even better. Thanks!
