### ISSUE TITLE
$strapi find with 'Where' clause

### ISSUE THREAD

**Issue by minyou9** [nuxt-community/strapi-module#129]
Hey guys,

I have looked into Strapi Nuxt module but I couldn't find any examples with the 'Where' clause

I have this simple code here to get the products with the filter but somehow it does not work. I checked the Network Tab and it turns out something like **_where: [Object, Object].**
` const searchProduct = async () => {
      this.products = await this.$strapi.$products.find({
      _where: { 
          Hide_Item: false, 
          tags: {
              Tag_Name: { _contains: this.products },
         },
      },
    })
 }`

Can anyone enlighten me on this? Much appreciate!

**Comment by drewtownchi** [comment]
To answer this question for a future read (as I had to figure this out as well) you need to use the [qs](https://github.com/ljharb/qs) library.

```
const stringify = require('qs/lib/stringify')

const searchQuery = stringify({
   _where: {
      _or: [
        { description_contains: this.searchQuery },
        { name_contains: this.searchQuery }
      ]
    }
})

// If you have other parameters outside the where you need to put them after the where clause.  
// This was throwing me off as I tried to merge the where clause into the parameters object.
this.searchResults = await this.$strapi.find('restaurants', searchQueryJson, {  active_eq: true })
````
