### ISSUE TITLE
critical HTTPError Forbidden on `$ nuxt generate` coming from `node_modules/ky/`

### ISSUE THREAD

**Issue by katerlouis** [nuxt-community/strapi-module#134]
### Version
@nuxtjs/strapi: v0.3.1
nuxt: v2.15.4

I fear this is specific to my use case so I cannot deliver a minimal reproduction, only a screenshot and the code that's causing it.

![image](https://user-images.githubusercontent.com/1983382/115589891-acbe9300-a2d0-11eb-8da0-192dac2f39f3.png)

Generating with `$ nuxt generate` went fine until I added this in `nuxtServerInit()`

```js
const strapiResult = await $strapi.find('upload/files');
const lottieFiles = strapiResult.filter(x => x.ext === '.json').map((x) => {
  return {
    id: x.id,
    name: x.name,
    url: `https://cms.my-domain.com${x.url}`,
    alt: x.alternativeText,
    mimeType: x.mime,
    hash: x.hash,
  };
});

commit('SET_LOTTIE_FILES', lottieFiles);
```

**Comment by katerlouis** [comment]
gentle push.
This issue still remains and I have no idea what to do :(

**Comment by Stubbs** [comment]
I have the same issue, it's down to a lack of credentials or API key so Strapi is rejecting the API call.

The documentation covers authentication of an actual user using the site, but not to call the API to generate the static pages (in my case)

If one of the authors can give an example of config to allow `nuxt generate` to access the API I'll update the docs.

**Comment by benjamincanac** [comment]
Closing this as the module has been rewritten in Nuxt3.

Also, you shouldn't generate pages that requires authentication, you can exclude those pages with [generate.exclude](https://nuxtjs.org/docs/configuration-glossary/configuration-generate#exclude).

Feel free to reopen if the issue persists.
