### ISSUE TITLE
Types & shortcuts generation on load

### ISSUE THREAD

**Issue by Stun3R** [nuxt-community/strapi-module#147]
### Is your feature request related to a problem? Please describe.
For the moment, you can only provide in `options` what content type you have on your Strapi API. Every time you'll add one in Strapi you'll have to update your module configuration.

### Describe the solution you'd like
As I said to @Atinux, I'm writing a global Strapi SDK which will include this feature. Indeed you'll be able to install a Strapi plugin on your Strapi API which will expose all your content types & the json-schema for each content type in order  to generate types based on it.

Thanks some packages, you can generate Typescript types based on json-schema:
```json
"schemas": [
    {
      "$schema": "http://json-schema.org/schema#",
      "title": "Test",
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "global": {
          "type": "string"
        },
        "testenum": {
          "enum": [
            "Value1",
            "Value2"
          ]
        },
        "testjson": {
          "type": "any"
        }
      }
    }
  ]
```
Will give this type:
```ts
export interface Test {
  title?: string;
  content?: string;
  global?: string;
  testenum?: "Value1" | "Value2";
  testjson?: unknown;
  [k: string]: unknown;
}
```

The plugin will be soon available within 2 weeks and we could start to work on this feature and implements it in order to use it in the `buildModule` feature from Nuxt.

**For the shortcuts methods generation**, the plugin will provide a collection like the following in order to let you generate those methods:
```json
"contentTypes": [
    {
      "name": "test",
      "type": "collectionType"
    },
    {
      "name": "homepage",
      "type": "singleType"
    }
  ]
```

**Comment by benjamincanac** [comment]
@Stun3R What do you think of closing this issue as you implemented it in your [Strapi SDK](https://strapi-sdk-js.netlify.app/) and we removed the `entites` from the Nuxt 3 version of this module?

**Comment by Stun3R** [comment]
> @Stun3R What do you think of closing this issue as you implemented it in your [Strapi SDK](https://strapi-sdk-js.netlify.app/) and we removed the `entites` from the Nuxt 3 version of this module?

Sure 👍🏼
