### ISSUE TITLE
Is it possible to pull draft items from a collection? 

### ISSUE THREAD

**Issue by liamb13** [nuxt-community/strapi-module#148]
Trying to figure out if it's possible to pull draft items in using the strapi module?

**Comment by logicminds** [comment]
Goes something like this:

`let data = await this.$strapi.find('articles', {  _publicationState: "preview" })`

**Comment by jakubmirejovsky** [comment]
> Goes something like this:
> 
> `let data = await this.$strapi.find('articles', { _publicationState: "preview" })`

Sure thing! But it would be great to have the **params** option available in findOne as well.

**Comment by benjamincanac** [comment]
@jakubmirejovsky This is now possible since v0.3.4 with params options available in `findOne`.
