### ISSUE TITLE
Is it possible for  use findOne (id ) or findOne (slug) with locale parameters for support strapi i18n

### ISSUE THREAD

**Issue by likelovewant** [nuxt-community/strapi-module#149]
Hi ,  I am facing an issue for get a single page or single type item from strapi collection type . i can not get a  required item or post from strapi by  findOne (slug , { _locale:i18n.locale})  for _slug.vue page , that's make my whole project stop  there . since it's required a locale parameter  to fetch other language for the item or post by slug . any idea  ,how to achieve that or there is any other alternative option for this module rather than use graphql or apollo .

thanks in advance 

Kevin

**Comment by reliut-g** [comment]
https://strapi.io/documentation/developer-docs/latest/development/plugins/i18n.html#usage-with-strapi-content-api

**Comment by benjamincanac** [comment]
Closing this as query params for [findOne](https://strapi-v0.nuxtjs.org/strapi#findoneentity-id-params) have been added in https://github.com/nuxt-community/strapi-module/pull/167 and released in https://github.com/nuxt-community/strapi-module/releases/tag/v0.3.2.
