### ISSUE TITLE
How to access collection with hyphen using $strapi.$collection-name

### ISSUE THREAD

**Issue by liamb13** [nuxt-community/strapi-module#151]
Trying to work out how to access a collection with a hyphen in it's name.
E.g `$strapi.$post-categories.find()`

As per: https://github.com/strapi/strapi/issues/8766 hyphens need to be enclosed with an array.

But trying `$strapi.$['post-categories'].find()` returns: `Cannot read property 'post-categories' of undefined`.

I can use: `$strapi.find('post-categories')` but to keep things consistent I was hoping to work with: `$strapi.$post-categories.find()`

Is this possible? Or should I be using `$strapi.find()` anyway?

**Comment by reliut-g** [comment]
@liamb13 are you using the `entities` property of the strapi config?

**Comment by benjamincanac** [comment]
Closing as issue is stalled.
