### ISSUE TITLE
Extend NuxtStrapiQueryParams with array support for more complex update/create payloads

### ISSUE THREAD

**Issue by SwitzerChees** [nuxt-community/strapi-module#161]
I have the problem that when I have a M:N relation in the strapi backend and I want to update these relations now I can't just easily fill the payload or how you call it **NuxtStrapiQueryParams** because arrays are not allowed and I get the following typescript error:
![image](https://user-images.githubusercontent.com/26026462/132248167-acd91da9-4bfc-4d5c-8d5f-5e695219bba1.png)
Now of course this is not an issue if you use just plain javascript but if you want to use this module with typescript it is really frustrating.

Now my question is, is it possible to just use a custom type definition for the create and update function for example called **NuxtStrapiPayload** like this:
![image](https://user-images.githubusercontent.com/26026462/132248313-1c0e8245-9ae5-4e0c-995e-9afbb3f33c07.png)

And there you allow also **Array<string | number | boolean>** for the key values like this:
![image](https://user-images.githubusercontent.com/26026462/132248352-07a3b16d-45f0-46d7-a807-58190193f180.png)

Because this way I am able to use the update function also for more complex relations without this annoying typescript error:
![image](https://user-images.githubusercontent.com/26026462/132248418-56f2384d-ad4f-48f7-8098-216527727973.png)

Here is my proposal hopefully you can integrate it as soon as possible 😉.

```typescript
export type NuxtStrapiPayload =
  string |
  {[key: string]: string | number | boolean | Array<string | number | boolean>} |
  Array<Array<string | number | boolean>> |
  URLSearchParams
```

and

```typescript
  create<T = any, E = string> (entity: E, data: NuxtStrapiPayload): Promise<T> {
    return this.$http.$post<T>(`/${entity}`, data)
  }

  update<T = any, E = string> (entity: E, id: string, data: NuxtStrapiPayload): Promise<T> {
    if (typeof id === 'object') {
      data = id
      id = undefined
    }
```

**Comment by benjamincanac** [comment]
@SwitzerChees Closing this as the module has been completely rewritten in Nuxt 3, if you didn't find a workaround feel free to reopen this issue or open a PR from the `v0-support` branch to add this to the types.
