### ISSUE TITLE
Properties USER change after reload

### ISSUE THREAD

**Issue by tanlong14** [nuxt-community/strapi-module#162]
### Version
@nuxtjs/strapi: 0.3.1
nuxt: 2.15.8 with i18n active
strapi: 3.6.8 with i18n active

### Problem
I have on the "user" types collection add additional fields (sample: avatar type "single media images")
On the website, once connected, I find these additional fields in the user object. If I refresh website, these additional fields disappear.

### Steps to reproduce
1- In admin strapi, create field "media" in collection "user" with this propertie:

- base settings: avatar (name), single media (type)
- advanced settings : images (type of media)

2- In website, create a login form who get user info:
```
const user = await this.$strapi.login({ identifier: this.model.username,  password: this.model.password, })
```

3- In another page of website, I get info of user
```
this.user = await this.$strapi.user
 console.log(this.user)
```

=> Result of log (**OK**), I have object "avatar": 
```
avatar: Object
blocked: false
confirmed: true
created_at: "2021-09-03T09:12:03.889Z"
email: "admin@example.com"
id: 1
initials: "at"
provider: "local"
role: Object
updated_at: "2021-09-08T12:39:39.982Z"
```

3- Now, I refresh my website with 'F5'
```
this.user = await this.$strapi.user
 console.log(this.user)
```

=> Result of log (**KO**), I loose object "avatar":
```
blocked: false
confirmed: true
created_at: "2021-09-03T09:12:03.889Z"
email: "admin@example.com"
id: 1
initials: "at"
provider: "local"
role: Object
updated_at: "2021-09-08T12:39:39.982Z"
username: "admin user test"
```

But with the another specific field "initials" (type "small text"), I don't have a problem

Why object "user" loose the field "avatar" after refresh ?

**Comment by madsh93** [comment]
Hi @tanlong14

This is not a bug. Since Strapi provides different API for auth and user. What you see is first the Auth API which provides you with all the info. On refresh you see the user/me API.

You should adjust in Strapi what is returned from the user/me API.

**Comment by tanlong14** [comment]
Hi @madsh93 ,

I do not think so.
The param "initials" is also a new property like param "avatar". And for this property, I have the information after the refresh.

**Comment by madsh93** [comment]
@tanlong14 check your API calls in developer tools, it sounds like two different calls. Your issue seems like #103

**Comment by tanlong14** [comment]
@madsh93 
OK thanks a lot
I did not see the other request, sorry.

**Comment by madsh93** [comment]
No worries. Let me know if you need help. 😊

**Comment by tanlong14** [comment]
The solution, if anyone needs it:

1- Create file "User.js" in folder: "./extensions/users-permissions/services/"

2- In file "User.js" write this:

`module.exports = {
  async fetchAuthenticatedUser(id) {
    return strapi
      .query("user", "users-permissions")
      .findOne({ id }, ["role", "avatar"]);
  },
};
`
