### ISSUE TITLE
Add support for Strapi version 4 Beta

### ISSUE THREAD

**Issue by madsh93** [nuxt-community/strapi-module#163]

**Comment by Tragio** [comment]
@Stun3R as you know v4 was launched today 😍 do you have any ETA for update this module? Thank you!

**Comment by Celibioux** [comment]
@Stun3R the greate V4 of Strapi is here finally <3 please tell us that we can use this module with it any time soon ?

**Comment by Stun3R** [comment]
@Tragio @Celibioux 

As I know @benjamincanac is working hard to make it available with nuxt3. For myself, I just released the v2 of native Strapi SDK which supports Strapi v4 https://strapi-sdk-js.netlify.app/

We'll discuss to integrate this one to this nuxt module in order to make it available for v3 & v4

**Comment by alexchudnovsky** [comment]
@Stun3R  are there any updates on the release for v4 :-) ?

Kind Regards,
Alex

**Comment by ChrisRM** [comment]
The API for Strapi v4 is now located at `http://host/api`, so a temporary fix would be to set the URL-configuration to `http://localhost:1337/api`.

```js
export default {
    url: 'http://localhost:1337/api', // Instead of http://localhost:1337
    strapi: {
        entities: ['products']
    },
    // ....
}
```

**Comment by jameshhood** [comment]
Right now I'm only able to get base level attributes back but absolutely no components get returned. I'm assuming this is due to their new API?

**Comment by alexchudnovsky** [comment]
@jameshhood 

have you tried 

https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#relations-population

**Example**

Get all relations nested inside a "navigation" component in the "global" single type

GET /api/global?populate[navigation][populate]=*

**Comment by miracleonyenma** [comment]
@alexchudnovsky Thanks for pointing that out, but how can you populate data using the $strapi hook? 
Let's say you're trying to get media data from your _articles_ collection which has a field for media called "cover_images" ?

**Comment by ricafolio** [comment]
> The API for Strapi v4 is now located at `http://host/api`, so a temporary fix would be to set the URL-configuration to `http://localhost:1337/api`.
> 
> ```js
> export default {
>     url: 'http://localhost:1337/api', // Instead of http://localhost:1337
>     strapi: {
>         entities: ['products']
>     },
>     // ....
> }
> ```

workaround for `strapi.graphql({...})` if it is requesting to `/api/graphql` instead of `/graphql`

```
this.$strapi.$http.$post('http://localhost:1337/graphql', {
      query: yourImportedGQLHere,
      variables: {
        someVar: someVal
      }
})

```

**Comment by Stun3R** [comment]
Hi @alexchudnovsky @Tragio @Celibioux ,

If you want a workaround for `Strapi v4`, you can check the guide here to use the native SDK in Nuxt: https://strapi-sdk-js.netlify.app/going-further/integrations/

**Comment by hoektoe** [comment]
Any updates on this development since Strapi v4 has been released?

I mistakenly thought all your starters are broken :)

**Comment by Stun3R** [comment]
> Any updates on this development since Strapi v4 has been released?
> 
> 
> 
> I mistakenly thought all your starters are broken :) 
> 
> 
> 
> Also what is the advantages of using the nuxtjs/strapi module over the SDK. SDK installation looks very simple.

It is mainly an integration of the SDK (big inspiration of it) and add composable stuff for nuxt3 but if you stick with nuxt2 or don't want too much things on the top the SDK is what you need

**Comment by benjamincanac** [comment]
The Strapi module has just been released in `v1.0.0` for Nuxt 3 and it supports Strapi v3 and v4 by changing the `version` key in your options which will provide composables and types for the specified version: https://strapi.nuxtjs.org/usage#usestrapi34.

We haven't been able to integrate the sdk as we wanted to take full advantage of the composition api and Nuxt 3 internals like `$fetch (ohmyfetch)`, `useCookie`...

@Stun3R Don't want to make a scene here, but the SDK code is itself based on the first version of the strapi-module. 

@hoektoe If you're using Nuxt2 with Strapi v4, I suggest you go for the Strapi SDK as only the `v1.0.0` of this module (nuxt 3) supports Strapi v4. Otherwise, you can use the one that best suits your needs or preferences.

**Comment by Stun3R** [comment]
@benjamincanac I never said it was a bad thing 🙌🏻 I'm glad that this module is finally released and happy we can complete each other 🥰 It's a great thing for nuxt3 to have this one. By the way, I will redirect user who look for nuxt3 integration of the SDK to this module by telling them in the documentation

(The SDK is an update of my nuxt module code I made before strapi-module exist: https://strapi-sdk-nuxtjs.netlify.app/ and inspired in some part of your module ☺️)

**Comment by Stun3R** [comment]
> @Stun3R Sure no problem, sorry for misunderstanding! I wish there was a way to integrate the SDK directly into the module but I don't see how for now, open to suggestions though.

As you use composable it would be hard to integrate it 🧐 The best way of doing it would have to extend the Strapi class of the SDK and add nuxt stuff inside of it

**Comment by jameshhood** [comment]
So the production version of strapi v4 with this module only works currently with a beta version of nuxt... not the production version v2?

**Comment by larbish** [comment]
@jameshhood Yes it is. Framework team is working hard to get Nuxt3 production ready. 
Here is a recap of which module version you should use with the corresponding nuxt version: 
- Nuxt2 / Strapi3 => Strapi module v0.3.x
- Nuxt2 / Strapi4 => You can use the [sdk](https://strapi-sdk-js.netlify.app/going-further/integrations/) of @Stun3R 
- Nuxt3 / Strapi3 => Strapi module v1.x.x
- Nuxt3 / Strapi4 => Strapi module v1.x.x
