### ISSUE TITLE
Ignore Cases

### ISSUE THREAD

**Issue by Intevel** [nuxt-community/strapi-module#175]
### Is your feature request related to a problem? Please describe.
I just tried to user in my database for a value with $strapi.find(), however it is case sensitive (which is good).
However, I couldn't find an option to use some kind of ignoreCase or anything similar to fix this problem. Because it should also work if you don't pay attention to upper and lower case in the parameters.

### Describe the solution you'd like
An option to ignore cases.

**Comment by Stun3R** [comment]
Hi @Intevel,
Could you provide some code snippet in order to help us understand well your issue? ☺️
