### ISSUE TITLE
Only absolute URLs are supported when in production

### ISSUE THREAD

**Issue by esiao** [nuxt-community/strapi-module#182]
### Version
@nuxtjs/strapi: ^0.3.1
nuxt: ^2.15.7

### Steps to reproduce
Use in a function like asyncData
```
  async asyncData (ctx: Context) {
    const page = await ctx.$strapi.find('homepage')
    return {
      page
    }
  }
  ```
  
  Run in development mode, no issues.
  
Run in production with nuxt start after nuxt build the server crashes with the error "Only absolute URLs are supported when in production".

This issue is reported by the nuxt/http module.

### What is Expected?

The URL setting from the Nuxt config should be prepended to the fetch queries. This seems to be the case with `this.$http.setBaseURL` inside of the strapi.js file.

### What is actually happening?

It looks like for some reason the baseURL is ignored and relative paths are used.

### Config

```
  strapi: {
    entities: [
    ...
    ],
    url: process.env.API_BASE_URL
  },
  ```
  
  with a .env file containing
  
  ```
  API_BASE_URL="http://localhost:1337"
  ```

**Comment by benjamincanac** [comment]
Hi @esiao,

Do you still have this error? This is weird as I've been using this module in production for quite some time now. Would you mind providing a basic reproduction?

**Comment by esiao** [comment]
Hi @benjamincanac, I'm sorry the project was on a hiatus I just worked again on it today. It did work today and I believe what I did wrong was to not run the server in the production environment through pm2 which defaults to dev.
Here's my pm2 `ecosytem.config.js` config file:
```
module.exports = {
  apps: [
    {
      name        : '[hidden]',
      script      : './node_modules/.bin/nuxt',
      args        : 'start',
      instances   : 'max',
      exec_mode   : 'cluster',
      wait_ready: true,
      listen_timeout: 5000,
      env: {
        NODE_ENV: 'development'
      },
      env_production: {
        NODE_ENV: 'production'
      }
    }
  ]
}

```
