### ISSUE TITLE
Release of version 1.0.0

### ISSUE THREAD

**Issue by kmuip** [nuxt-community/strapi-module#186]
Hello

I closely followed pr #168 and #183.
Both have been closed or merged and the latter bumped the modules version to 1.0.0.

Do you know when it will be released?

Best regards
Lukas

**Comment by benjamincanac** [comment]
Hello Lukas,

We're still testing the module internally and polishing things up with `nuxt3`. Also, there is still a bit of documentation left to do but the release should happen really soon.

In the meantime, you can use `edge` version representing the `dev` branch by following the documentation here: https://github.com/nuxt-community/strapi-module/blob/dev/docs/pages/2.setup.md#edge-channel

**Comment by kmuip** [comment]
Hi Benjamin

Awesome, can't wait for the release.

Thanks for the fast reply and the recommendation, I'll use the edge version for now :)

Regards
Lukas

**Comment by michelwaechterimflow** [comment]
Do you need help on documentation or maybe translation?
