### ISSUE TITLE
Possible changes to the StrapiRegistrationData interface

### ISSUE THREAD

**Issue by luke-z** [nuxt-community/strapi-module#189]
Hello guys, I have a small feature request :)

### Is your feature request related to a problem? Please describe.
I'm currently working on a registration form and wanted to add a phone number to the registration payload.
However, the interface is limited to username, email and password.

### Describe the solution you'd like
It would be cool if the registration payload could be filled with custom properties, for example a phone number.
All properties that are on the user can be added to it on registration. 

The critical properties `confirmed`, `confirmationToken` and `resetPasswordToken` are omitted before the user is created. The only user property the endpoint can manipulate on registration, next to `username`, `email` and `password`, is `blocked`. I don't think that this is a security issue.
But it could become a problem if for example a premium membership flag is stored on the user. Which means that these properties could be manually set on registration. This is however already possible on a default strapi instance with additional properties on the user content type.

The question now is, which of these scenarios is more likely? The need for custom properties on registration or restricting the possible properties for security reasons? :)

I was thinking of the following addition to the [StrapiRegistraionData](https://github.com/nuxt-community/strapi-module/blob/c4606172ecb79bd0d5149daa3da280415ae50c4e/src/types/index.ts#L560) interface:

    export interface StrapiRegistrationData {  
      username?: string
      email: string
      password: string
      [additionalProperties: string]: string | number | boolean | Array<string | number | boolean> <-- might not be complete
    }

Do you think this is possible?

### Describe alternatives you've considered

Another way would be to create the user and then immediately update it with the phone number.
This is a rather complicated way as the user update endpoint would need to be secured to allow personal updates only.

In a large scale application with user settings, etc. this could be a valid workaround, as the update endpoint would need to be exposed anyway.

Best regards,
Lukas

**Comment by benjamincanac** [comment]
@luke-z Indeed, we should update the types to support this. A similar issue https://github.com/nuxt-community/strapi-module/issues/161 was created to support this in the previous version of the module.

Feel free to open a PR or I'll take care of it next week 🙂

**Comment by luke-z** [comment]
@benjamincanac sure, I'll do as much as a can!

What a nice coincidence, that issue was opened by my friend :) 
Just came across that type issue again since we're moving back to REST from graphql in the same project that issue arose (still on v0 until nuxt3 is out of beta). Just was exploring the type file this morning :)

Maybe we'll open a PR for both, v0 & v1.

**Comment by benjamincanac** [comment]
@luke-z It would be awesome 🚀 

FYI if you're opening a PR for the `v0` version, you have to set `v0-support` as the base branch.
