### ISSUE TITLE
Property "$strapi" was accessed during render but is not defined on instance / 'entities' does not exist in type 'StrapiOptions'.

### ISSUE THREAD

**Issue by jannikbuscha** [nuxt-community/strapi-module#200]
### Version
@nuxtjs/strapi: 0.3.4
nuxt: latest

IDE: PhpStorm

### Reproduction/Steps to reproduce

completely empty and new nuxt3 project

### What is actually happening?'

Hey, as soon as I want to set up a new nuxt3 project with strapi I get the following error:

TS2345: Argument of type '{ buildModules: string[]; strapi: { url: string; }; }' is not assignable to parameter of type 'NuxtConfig'.   Object literal may only specify known properties, and 'strapi' does not exist in type 'NuxtConfig'.

I actually did it the same way as in the "example", except that I specified "'@nuxtjs/strapi'" instead of "module", as it also says in the doc.

nuxt.config.ts
![image](https://user-images.githubusercontent.com/74017697/147726516-37fcc942-a1fd-4889-8179-a923aa104edc.png)

**Comment by jannikbuscha** [comment]
Could fix the IDE error with this:

`import type { StrapiOptions } from '@nuxtjs/strapi';

declare module '@nuxt/schema' {
  interface NuxtConfig {
    strapi?: StrapiOptions;
  }
  interface NuxtOptions {
    strapi?: StrapiOptions; 
  }
}`

But the startup error remains:
![image](https://user-images.githubusercontent.com/74017697/147896660-6fb2f85e-c01c-41df-b76b-b18cdc63be66.png)
![image](https://user-images.githubusercontent.com/74017697/147896666-592785be-16a9-4de9-9337-004ce1fa8bf9.png)

**Comment by kmuip** [comment]
Hi Jannik

You need to use the edge channel version of the @nuxtjs/strapi package at the moment.
Version 0.3.4 is not compatible with Nuxt3.

**Comment by jannikbuscha** [comment]
> Hi Jannik
> 
> You need to use the edge channel version of the @nuxtjs/strapi package at the moment. Version 0.3.4 is not compatible with Nuxt3.
> 
> https://github.com/nuxt-community/strapi-module/blob/dev/docs/pages/2.setup.md#edge-channel

Nice, the errors are all gone so far, however I don't know what else it needs to recognize `$strapi` now:
![image](https://user-images.githubusercontent.com/74017697/148001295-f2e1e755-04f7-49b0-98c5-e77790e5cdd6.png)

**Comment by jannikbuscha** [comment]
I have now added ConfigSchema in my `nuxt-schmea-shim.d.ts`, where now comes the following error:
Also, `entities` is not recognized. I will probably switch to the native `strapi-sdk` for now.
![image](https://user-images.githubusercontent.com/74017697/148004910-ddb95001-3855-4ee3-9b2b-d394ca21361a.png)
![image](https://user-images.githubusercontent.com/74017697/148004896-3e6422fa-912d-4e4a-8ae4-22ebdd2dffde.png)

**Comment by kmuip** [comment]
In Nuxt3 there is no $strapi.

You can access the methods trough composables which are explained here https://github.com/nuxt-community/strapi-module/blob/dev/docs/pages/3.usage.md

The methods are either in `useStrapiAuth()` or in `useStrapi{3|4}()`, depending on the Strapi version you are using.

**Comment by jannikbuscha** [comment]
> In Nuxt3 there is no $strapi.
> 
> You can access the methods trough composables which are explained here https://github.com/nuxt-community/strapi-module/blob/dev/docs/pages/3.usage.md
> 
> The methods are either in `useStrapiAuth()` or in `useStrapi{3|4}()`, depending on the Strapi version you are using. All the strapi module composables are automatically imported.
> 
> Regarding the config:
> 
> The edge package should be in the package.json devDependencies as such: `"@nuxtjs/strapi": "npm:@nuxtjs/strapi-edge@latest"`
> 
> The module then needs to be in the buildModules section in nuxt.config.ts `buildModules: ['@nuxtjs/strapi']`
> 
> These are the default options:
> 
> ```
>   strapi: {
>     url: process.env.STRAPI_URL || 'http://localhost:1337',
>     prefix: '/api',
>     version: 'v4',
>   },
> ```
> 
> If the rest of your Nuxt3 setup is correct then the strapi module will work.

he also does not find the method
![image](https://user-images.githubusercontent.com/74017697/148029563-1d96d177-6ca4-429f-a3da-3d476be5d316.png)
![image](https://user-images.githubusercontent.com/74017697/148029572-83249135-2d5a-4c4d-9734-2c238177f806.png)
![image](https://user-images.githubusercontent.com/74017697/148029744-5c56e1a0-d341-4907-9c34-6db0e9da0787.png)
![image](https://user-images.githubusercontent.com/74017697/148029772-dd30708d-8d72-41b1-b861-7e506d87eec0.png)

**Comment by jannikbuscha** [comment]
> > In Nuxt3 there is no $strapi.
> > You can access the methods trough composables which are explained here https://github.com/nuxt-community/strapi-module/blob/dev/docs/pages/3.usage.md
> > The methods are either in `useStrapiAuth()` or in `useStrapi{3|4}()`, depending on the Strapi version you are using. All the strapi module composables are automatically imported.
> > Regarding the config:
> > The edge package should be in the package.json devDependencies as such: `"@nuxtjs/strapi": "npm:@nuxtjs/strapi-edge@latest"`
> > The module then needs to be in the buildModules section in nuxt.config.ts `buildModules: ['@nuxtjs/strapi']`
> > These are the default options:
> > ```
> >   strapi: {
> >     url: process.env.STRAPI_URL || 'http://localhost:1337',
> >     prefix: '/api',
> >     version: 'v4',
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If the rest of your Nuxt3 setup is correct then the strapi module will work.
> 
> he also does not find the method ![image](https://user-images.githubusercontent.com/74017697/148029563-1d96d177-6ca4-429f-a3da-3d476be5d316.png) ![image](https://user-images.githubusercontent.com/74017697/148029572-83249135-2d5a-4c4d-9734-2c238177f806.png) ![image](https://user-images.githubusercontent.com/74017697/148029744-5c56e1a0-d341-4907-9c34-6db0e9da0787.png) ![image](https://user-images.githubusercontent.com/74017697/148029772-dd30708d-8d72-41b1-b861-7e506d87eec0.png)

oh this is a bug from my ide, got it fixed. Thanks for everything :)
