### ISSUE TITLE
Best practice accessing populated fields in Strapi4 response

### ISSUE THREAD

**Issue by kmuip** [nuxt-community/strapi-module#203]
Hello :)

I was just playing around and saw that populated fields are returned with the same structure as the "parent" 

```
   export interface Strapi4ResponseData<T> {
     id: number,
     attributes: T,
     meta: Record<string, unknown>
   }
```

Accessing such a field would result in 
`response.data[0].attributes.populated_field.data.attributes`

In my case, I populated a media field containing one picture.

Quite the difference from the Strapi3 response.

What would you recommend in terms of storing such a response in store (I'm currently using pinia) and accessing the data as efficient as possible?

**Comment by kmuip** [comment]
This is the discussion in the strapi forum: https://forum.strapi.io/t/discussion-regarding-the-complex-response-structure-for-rest-graphql-developer-experience/13400

**Comment by benjamincanac** [comment]
Hey @kmuip,

I've ran into this issue as well, I didn't use the `Strapi4Response` at all (this is why it is not by default in the module) and override all the controllers by removing [this.transformResponse](https://github.com/strapi/strapi/blob/master/packages/core/strapi/lib/core-api/controller/collection-type.js#L27).

If you don't want to do this, you'd have to use the `Strapi4Response` inside your own types I guess.

**Comment by luke-z** [comment]
Hi @benjamincanac, replying from my personal account :)

Thank you for the reply!
I think editing those controllers results in a lot of maintenance.

After going through the forum post, I tried to implement such a destructuring function myself.

Here is the function I wrote, maybe it helps someone in the future:

```
const destructure = (payload) => {
  const handle = (data) => {
    const obj = {}
    const { id, attributes } = data

    for (const key in attributes) {
      const attribute = attributes[key]

      if (_.has(attribute, 'data')) {
        obj[key] = destructure(attribute.data)
        continue
      }

      obj[key] = attribute
    }

    obj['id'] = id

    return obj
  }

  if (_.isArray(payload)) {
    const arr = []
    for (const element of payload) {
      const obj = handle(element)

      arr.push(obj)
    }
    return arr
  }

  return handle(payload)
}
```

I put this in a global middleware executing after the controller. Calling the function looks like that:

`ctx.body.data = destructure(ctx.body.data)`

I will have to make sure that it doesn't execute on auth responses.
Also, I haven't tested it on components yet, just on simple content types with relations.

Like this it will create a Strapi3 kind of response.

```
{
  data: { }, // object or array of objects with the results without data & attributes in the tree
  meta: {}
}
```

**Comment by benjamincanac** [comment]
Closing this as I dont have any more informations on how to achieve this.

@luke-z If you feel your solution is ready, don't hesitate to make a PR to the documentation in `Advanced` section to explain how to achieve this, maybe the solution described here https://github.com/nuxt-community/strapi-module/issues/204 can be usefull too.

**Comment by jch-code** [comment]
I created a tool to handle this issue for myself, [strapi-parse](https://github.com/jch-code/strapi-parse).

I have only used it on a small sample size in my own projects, so I wouldn't be surprised if I missed some edge cases, but it works for me on some fairly complex objects with populated fields, dynamic zones, & repeatable components.
