### ISSUE TITLE
Strapi4Response | get direct object from interface

### ISSUE THREAD

**Issue by jannikbuscha** [nuxt-community/strapi-module#204]
Hey, how do I get the perfect object field right away when working with `Strapi4Response`. I have to specify an interface according to the documentation, but this has no use, I get the complete json from the request every time and have to attach `.data.attributes` to it every time.
![image](https://user-images.githubusercontent.com/74017697/148034557-70148080-c547-4902-a333-04adbc9aedbe.png)
My interface:
![image](https://user-images.githubusercontent.com/74017697/148034602-f8bc6a96-f3bb-488a-a040-6d44685c959b.png)
My result:
![image](https://user-images.githubusercontent.com/74017697/148034648-bf32e262-fde2-4fe4-ab69-cc4dd7c7e998.png)

My sample solution I imagine is that I only need to make `response.header `

------
It would be also very helpful for me if someone can tell me why I have to specify an interface at all with `Strapi4Response`, because no matter what I specify it comes out the same.

**Comment by kmuip** [comment]
The interface you're providing is just TypeScript stuff, it doesn't change the response. It only types your response object.
The result you're talking about is how Strapi returns the data in version 4. (https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#unified-response-format)

I'm currently exploring the possibilities of how to easily access data in this type of response.
It's easy if there's just one level of data, e.g.:

```
const newObj = {
      id: data.id,
      ...data.attributes,
    }
```

but as soon as you have a populated field it gets nasty.

This is the question I asked a few hours before you, it's about best practices to do that: https://github.com/nuxt-community/strapi-module/issues/203

**Comment by jannikbuscha** [comment]
> The interface you're providing is just TypeScript stuff, it doesn't change the response. It only types your response object. The result you're talking about is how Strapi returns the data in version 4. (https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#unified-response-format)
> 
> I'm currently exploring the possibilities of how to easily access data in this type of response. It's easy if there's just one level of data, e.g.:
> 
> ```
> const newObj = {
>       id: data.id,
>       ...data.attributes,
>     }
> ```
> 
> but as soon as you have a populated field it gets nasty, just a nested mess of data & attributes:
> 
> ```
> {
>   data: {
>     id: 1,
>     attributes: {
>       title: 'example',
>       thumbnail: {
>         data: {
>           id: 1,
>           attributes: {
>             ....
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> This is the question I asked a few hours before you, it's about best practices to do that: #203

some actually don't like the way the api is built now, but i like the post of roelbeerens from the strapi forum where he shows his normalize method and i will use that.

**Comment by jannikbuscha** [comment]
> > The interface you're providing is just TypeScript stuff, it doesn't change the response. It only types your response object. The result you're talking about is how Strapi returns the data in version 4. (https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#unified-response-format)
> > I'm currently exploring the possibilities of how to easily access data in this type of response. It's easy if there's just one level of data, e.g.:
> > ```
> > const newObj = {
> >       id: data.id,
> >       ...data.attributes,
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but as soon as you have a populated field it gets nasty, just a nested mess of data & attributes:
> > ```
> > {
> >   data: {
> >     id: 1,
> >     attributes: {
> >       title: 'example',
> >       thumbnail: {
> >         data: {
> >           id: 1,
> >           attributes: {
> >             ....
> >           }
> >         }
> >       }
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is the question I asked a few hours before you, it's about best practices to do that: #203
> 
> some actually don't like the way the api is built now, but i like the post of roelbeerens from the strapi forum where he shows his normalize method and i will use that.

```ts
export default async function get<T>(collection: string, fields?: string[], one?: boolean) {
    const {findOne} = useStrapi4()
    const {find} = useStrapi4()

    return normalize(one
        ? await findOne<Strapi4Response<T>>(collection, 1, {
                populate: '*',
                fields: fields
            }
        ) : await find<Strapi4Response<T>>(collection, {
                populate: '*',
                fields: fields
            }
        )
    )
}
```

```vue
<script setup lang="ts">
import get, {Description} from '~/utils/useStrapi'

const response = await get<Description>('descriptions', ['header'], true)
</script>
```

**Comment by benjamincanac** [comment]
@jannikbuscha Thanks for example on how to normalize response from Strapi!
