### ISSUE TITLE
Change default branch to develop

### ISSUE THREAD

**Issue by Elliot67** [nuxt-community/strapi-module#205]
## Problem
The current homepage readme comes from the develop branch and explicitly states the module is compatible with Strapi v3/v4. While the current released is only compatible with Strapi v3.

## Solution
Change the default branch to main or add an indication inside the readme of the develop branch.

Would have prevented me from losing my mind  trying to figure out why the request parameters weren't working 😄 .
Might help other people

**Comment by benjamincanac** [comment]
Hey @Elliot67,

Sorry about that, we didn't want to publish during holidays. 

Just released the `v1.0.0` and the documentation has been updated accordingly.

Let me know if you have any issue with the new version.

**Comment by Elliot67** [comment]
Seems like there is no compatibility for Nuxt 2 with Strapi v4.
Kinda strange since Nuxt 3 hasn't been released yet (does it mean it's coming soon ? 👀)

**Comment by benjamincanac** [comment]
@Elliot67 Nuxt 3 is in beta right now, you can already start using it: https://v3.nuxtjs.org.

As for the module, we decided to only add new features to the Nuxt 3 version, the `v0.3.1` (nuxt 2) will only get bug fixes. 

If you really want to use Strapi v4 with Nuxt 2, you can check out the [Strapi SDK](https://strapi-sdk-js.netlify.app/) made by @Stun3R.
