### ISSUE TITLE
Cannot install on Nuxt 3

### ISSUE THREAD

**Issue by larrasu** [nuxt-community/strapi-module#206]
### Version
@nuxtjs/strapi: `latest`
nuxt: `latest`

### Steps to reproduce
- Fresh install of Nuxt 3 via `nuxi`
- Installed Tailwind + Headless UI
- Proceeds to install Strapi module but failed

### What is Expected?
Strapi module should be installed without problems.

### What is actually happening?
Error showing:
```bash
npm install @nuxtjs/strapi
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vue@3.2.26
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.0.0" from @headlessui/vue@1.4.2
npm ERR!   node_modules/@headlessui/vue
npm ERR!     @headlessui/vue@"^1.4.2" from the root project
npm ERR!   peer vue@"3.x" from @iconify/vue@3.1.1
npm ERR!   node_modules/@iconify/vue
npm ERR!     dev @iconify/vue@"^3.1.1" from the root project
npm ERR!   10 more (@nuxt/vite-builder, @nuxt/webpack-builder, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @nuxtjs/strapi@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@"^2.0.0" from vuex@3.6.2
npm ERR!   node_modules/vuex
npm ERR!     peer vuex@"*" from @nuxtjs/strapi@0.3.4
npm ERR!     node_modules/@nuxtjs/strapi
npm ERR!       @nuxtjs/strapi@"*" from the root project
```

As stated in the README and just to confirm, is Nuxt 3 supported?

**Comment by luke-z** [comment]
Hi Larra

Make sure you install the edge channel of the strapi-module for the moment as v0.3.4 does not yet include the recent changes for Nuxt3 compatibility:
https://github.com/nuxt-community/strapi-module/blob/dev/docs/pages/2.setup.md#edge-channel

Don't forget to add the module to the buildModules array in nuxt.config.ts:
`buildModules: ['@nuxtjs/strapi']`

After that you can follow the usage instructions:
https://github.com/nuxt-community/strapi-module/blob/dev/docs/pages/3.usage.md

Hope that helps :)

**Comment by larrasu** [comment]
Thank you! Installing the edge channel works.
