### ISSUE TITLE
Strapi4 No Graphql Implementation ?

### ISSUE THREAD

**Issue by Celibioux** [nuxt-community/strapi-module#207]
Thank you @benjamincanac for your amazing & hard work i was waiting this upgrade for a while 
i just wanna ask if there is any plan to implement Graphql as we use Strapi Graphql Plugin 

Thanks again

**Comment by benjamincanac** [comment]
Hey @Celibioux,

Indeed, this method went missing while migrating the module to Nuxt 3. I just released [v1.1.0](https://github.com/nuxt-community/strapi-module/releases/tag/v1.1.0) with a new [useStrapiGraphQL](https://strapi.nuxtjs.org/usage#usestrapigraphql) composable.

Let me know if you have any issue with it.

**Comment by Celibioux** [comment]
@benjamincanac Thank you for the amazing work
