### ISSUE TITLE
Fix types resolution in IDE

### ISSUE THREAD

**Issue by larbish** [nuxt-community/strapi-module#211]
Waiting for the module builder of the nuxt3 framework team.

**Comment by benjamincanac** [comment]
@pi0 I noticed you removed the types from the build dist in this PR: https://github.com/nuxt-community/strapi-module/pull/188/files#diff-e90114558fac0ebaf58c4b7cc5336fc7f8b4f5d518fdba37635d0c38291d128eL8, now when clicking on the type from the editor types are not found:
<img width="1028" alt="CleanShot 2022-01-14 at 14 33 42@2x" src="https://user-images.githubusercontent.com/739984/149523577-de7ed1c3-8b40-4b49-8d8e-bfbc932e204e.png">

**Comment by pi0** [comment]
Can you please explain issue better? `types/` seems to be bundled in [module.d.ts](https://unpkg.com/browse/@nuxtjs/strapi-edge@1.1.0-27369286.5893b15/dist/module.d.ts) properly. (same expected behavior of current module builder).

But I guess types of auto imported `useStrapi4` are missing right?

**Comment by benjamincanac** [comment]
Actually types are working great, the issue is only when clicking in VSCode on `../../types/v4` since `types/` dir is not bundled.

**Comment by pi0** [comment]
#213
