### ISSUE TITLE
Make it easier to debug graphql queries

### ISSUE THREAD

**Issue by merijnponzo** [nuxt-community/strapi-module#220]
When I have a wrong property within my graphql query I only see this error:

[Vue warn]: Unhandled error during execution of setup function 
  at <[slug] onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/favicon.ico" >
undefined

It's very hard to find out this comes from a wrong graphql query (400) since i had some props wrong in the query

It would be very nice if an error message where shown instead of the Vue warn above

**Comment by larbish** [comment]
@merijnponzo Once the PR has been merged, you should be able to see the details of you graphql error in the console above the Vue warning message. 
![image](https://user-images.githubusercontent.com/7290030/151164157-fd99cb42-a170-4f59-908b-526bfccc4797.png)
