### ISSUE TITLE
How to use API token in Nuxt3

### ISSUE THREAD

**Issue by IzakJackson** [nuxt-community/strapi-module#233]
Hi,

I'm not using user authentication on my app, but I'm wanting to protect my API with the API Token.

How can I put the API token into the header request?

```
await create<Strapi4Response<Subscriber>>("subscribers", {
      email: data.email,
    });
```

**Comment by Atinux** [comment]
From what I see here: https://github.com/nuxt-community/strapi-module/blob/e722d34b6d4a69e1b7d34d3807b636ba82a4b452/src/runtime/composables/useStrapiClient.ts#L52

We need to update https://github.com/nuxt-community/strapi-module/blob/dev/src/runtime/composables/useStrapi4.ts#L43-L45 in order to also forward the FetchOptions.

**Comment by Atinux** [comment]
I think a PR should be quite straightforward if you want to contribute @IzakJackson :grinning:

**Comment by IzakJackson** [comment]
@Atinux - pretty new to dev so not sure where I'd start 😅

**Comment by benjamincanac** [comment]
Hi @IzakJackson,

An easy solution for now could be to use the `client` directly, you can check out the documentation here https://strapi.nuxtjs.org/usage#usestrapiclient.

Here is an example:

```js
const client = useStrapiClient()

await client<Strapi4Response<Subscriber>>('/subscribers', {
  method: 'POST',
  body: {
    data: {
      email: data.email
    }
  },
  headers: {
     ...
  }
})
```

For informations, the `create` method is juste a wrapper around the `client`, you can check out the code here https://github.com/nuxt-community/strapi-module/blob/dev/src/runtime/composables/useStrapi4.ts#L43

**Comment by IzakJackson** [comment]
@benjamincanac Amazing, thanks!
