### ISSUE TITLE
Setting STRAPI_URL on runtime instead of on build

### ISSUE THREAD

**Issue by willempie96** [nuxt-community/strapi-module#234]
Hi, I'm trying to setup a nuxt3 - strapi v4 project to be able to run in a k8 cluster.
I'd like to be able to set the strapi url when the container starts by using the environment variables in my hosting provider.
But it seems the environment variable is fetched only on build, not on start.

I have been trying to use the publicRuntimeConfig because Nuxt3 docs say you can overwrite runtimeconfig values in production if you use the same variable name but i can't get it to overwrite the strapi url. Is this possible?

I have been trying to get this to work locally using:

nuxt.config.ts:
`  ...
publicRuntimeConfig: {
    STRAPI_URL: process.env.STRAPI_URL || 'localhost:1337'
  },
...`

.env:
`STRAPI_URL = "http://oldruntime.com"`

`
npm run build
STRAPI_URL='http://clruntime.com' npm run start
`

In my nuxt app i then log useStrapiUrl() and useRuntimeConfig():
useStrapiUrl():
`http://oldruntime.com/api`
useRuntimeConfig():
`
STRAPI_URL: "http://clruntime.com",
strapi:{
  cookie: {}
  prefix: "/api"
  url: "http://oldruntime.com"
  version: "v4"
}
`

So the STRAPI_URL is being overwritten in runtime but the strapi.url is still the same url as on build.

**Comment by NidMo** [comment]
I want to ask you if you have solved this problem

**Comment by willempie96** [comment]
Hi,

We found out that to override the public runtime config variables you need to set the config key to `NUXT_PUBLIC_STRAPI_URL` instead of STRAPI_URL. This was badly documented in the nuxt3 docs but this has been improved.

If you set up your runtime config like this:
`
runtimeConfig: {
    public: {
      strapi: {
        url: 'http://localhost:1337',
      }
    }
  },
`

You can override this on runtime by using `NUXT_PUBLIC_STRAPI_URL=api.live.com`

This could be a nice improvement to the docs of this module itself as well but that might be outside of the scope.

**Comment by pschaub** [comment]
You can override the url through the environment variable `NUXT_PUBLIC_STRAPI_URL`.
This is possible due to the implementation in the module: https://github.com/nuxt-community/strapi-module/blob/8db8b671aa4300cd5edae4a787c328dc55acc5b6/src/module.ts#L81-L97

**Comment by re2005** [comment]
Hi, sorry if this question sounds a bit silly.

I can't way to proxy the strapi url to the url where nuxt is running.

Lets say I'm running my strapi on a url `https://cms.lalala.io`

And I've my nuxt application running on `https://my-nuxt.io` 

Using the next3 proxy i can forward all traffic from  `https://my-nuxt.io/api` to  `https://cms.lalala.io`

```
    vite: {
        server: {
            proxy: {
                "/api": {
                    target: 'https://cms.lalala.io'
                },
            },
        },
    },
```

The problem is how to point this plugin to accept it own location as the url to be used.

```
    strapi: {
        url: ///// HERE I can't manage to tell @strapi/nuxt to use it own location.
        prefix: '/api',
        version: 'v4',
        cookie: {},
        cookieName: 'strapi_jwt',
    },
```

Please any help is welcome.
