### ISSUE TITLE
delete is not imported from useStrapi4

### ISSUE THREAD

**Issue by Aft1n** [nuxt-community/strapi-module#237]
### Version
@nuxtjs/strapi: 1.3.1 
nuxt: 3 

### Steps to reproduce
importing create, find and delete from useStrapi4
<img width="367" alt="Снимок экрана 2022-03-15 в 16 07 18" src="https://user-images.githubusercontent.com/54577662/158400293-bf7fbaee-9555-4ae2-8bef-4de0df099303.png">

### What is Expected?
delete being imported and function working as others

### What is actually happening?
adding "delete" giving an error in IDE and not working in script

**Comment by Aft1n** [comment]
i have found that it is being imported and works fine if i import it as it is stated in strapi module files:  {delete: _delete} =useStrapi4()

But in the module usage examples it says nothing about such naming

**Comment by Intevel** [comment]
This can be closed.
