### ISSUE TITLE
useStrapiClient throw error

### ISSUE THREAD

**Issue by NidMo** [nuxt-community/strapi-module#241]
### Version
@nuxtjs/strapi: 1.3.1
nuxt: 3.0.0-27480376.fdd38f9

### Steps to reproduce

function getOne(slug: string) {
    const client = useStrapiClient()
    return client(`slugify/slugs/article/${slug}`)
  }

async setup(props) {

await useAsyncData('articles', async() => {
try {
        getOne(slug).then((res) => {
          console.log('res:', res)
        })
      }
      catch (error) {
        console.log('errro:', error)
      }
})
}
### What is Expected?

get data success
### What is actually happening?

throw error

![image](https://user-images.githubusercontent.com/24955673/161371016-d680cdce-3912-431f-ae7f-71dea04638d8.png)

**Comment by benjamincanac** [comment]
Hey @NidMo, you cannot use composables outside of the `setup` function, to make it work you move your function into your `setup`.
