### ISSUE TITLE
GraphQL Fetch

### ISSUE THREAD

**Issue by joelbqz** [nuxt-community/strapi-module#26]
### Is your feature request related to a problem? Please describe.

I'm using Nuxt + Strapi on a medium-sized web application(I haven't used this module in any real project yet, but willing to). The issue I currently face is most of the time I'm using REST, but for some parts of the app a GraphQL query will do the job better(multiples queries in just 1 HTTP request for example), but making fetch/axios request to a GraphQL API without Apollo seems to require a lot of boilerplate.

### Describe the solution you'd like

I would love to have a method to perform graphql queries like:

```const data = await $strapi.graphql(query, vars);```

### Describe alternatives you've considered

```
const request = await this.$strapi.$http.$post('/graphql', {query, vars});
const {data} = await request.json();
```
The alternative seems a little bit verbose?

### Additional context
Let me know what do you guys think, If you think this feature is good to have I could help with a PR.

**Comment by joelbqz** [comment]
@benjamincanac 👀

**Comment by nonlinearcom** [comment]
This could be a killer feature!

**Comment by joelbqz** [comment]
> This could be a killer feature!

I already sent a pull request, waiting for someone to review it 😄
