### ISSUE TITLE
Can't access documentation page 

### ISSUE THREAD

**Issue by d3nyz** [nuxt-community/strapi-module#270]
When tying to access **https://strapi.nuxtjs.org/** getting 500 error with this message:
> Failed to fetch dynamically imported module: https://strapi.nuxtjs.org/_nuxt/fluid-7df30fe7.mjs

Tried yesterday and today. 
Tried to look for web archive, but it doesn't have all pages...

**Comment by danielroe** [comment]
Same issue occurred here: https://github.com/danielroe/magic-regexp/issues/36.

This is an ad-blocker blocking anything with `fluid` in the URL.

cc: @tahul - it may be worth renaming `fluid.vue` to something else or this issue could crop up everywhere with little explanation.

**Comment by d3nyz** [comment]
@danielroe got it, thank you!
