### ISSUE TITLE
fetchUser method doesn't work 

### ISSUE THREAD

**Issue by myfailemtions** [nuxt-community/strapi-module#4]
### Version
@nuxtjs/strapi: v0.1.0
nuxt: v2.13.0 

### Reproduction Link
https://github.com/nuxt-community/strapi-module/blob/master/lib/plugin.js#L88

### Steps to reproduce
- Install @nuxt/strapi
- Log in console `this.$strapi.user` 
- Try to login with`this.$strapi.login()` method
- User object appears in console
- Refresh the page
- User undefined

### What is Expected?
- Install @nuxt/strapi
- Log in console `this.$strapi.user` 
- Try to login with`this.$strapi.login()` method
- User object appears in console
- Refresh the page
- User still appears in console

### What is actually happening?
In the library, you using fetchUser method, what calling `this.getEntry('users', 'me')` but it's not a function.
Code goes to catch block and calling `this.clearToken()`

**Comment by benjamincanac** [comment]
@myfailemtions Thanks for your report, should be fixed in [v0.1.1](https://github.com/nuxt-community/strapi-module/releases/tag/v0.1.1).
