### ISSUE TITLE
Property '$strapi' does not exist on type

### ISSUE THREAD

**Issue by 3tew** [nuxt-community/strapi-module#47]
Hi, I have a problem with  `$strapi` in `pages/index.vue`. I already add  `@nuxtjs/strapi` in `nuxt.config.js` modules but why I got this error...

![Capture](https://user-images.githubusercontent.com/5137066/92394780-57bc7b00-f14c-11ea-82ee-3336e0d60f5a.PNG)

Or

![Capture2](https://user-images.githubusercontent.com/5137066/92397736-8852e380-f151-11ea-8565-963db2e93c00.PNG)

Can you guys give me some advice? thank.

**Comment by 3tew** [comment]
I try to use `({ $strapi }: any)` It's work.

```ts
export default {
  async asyncData({ $strapi }: any) {
    const response = await $strapi.graphql({
      query: `query {
                  productCategories {
                    id
                    name
                    image {
                      url
                    }
                  }
                }`,
    });

    return { productCategories: response };
  },
};
```

**Comment by hs-myudin** [comment]
but how we can extend CombinedVueInstance?
I dont want use cranches in code everytime....

**Comment by benjamincanac** [comment]
Unfortunately I have no knowledge on TypeScript, a PR would be more than welcome!

**Comment by hymair** [comment]
This is still an issue. 

"@nuxtjs/strapi": "^0.3.1"
"nuxt": "^2.15.3"
"@nuxt/types": "^2.15.3"
