### ISSUE TITLE
Losing some data from User object after page refresh

### ISSUE THREAD

**Issue by bubbleis** [nuxt-community/strapi-module#48]
### Version
@nuxtjs/strapi: ^0.1.6
nuxt: ^2.14.0

Hey guys, hi there!
The problem persists, but in another way.
And maybe i'm not doing something well.

### What is Expected?
The problem is next.
When i'm logging in, i have the next response for my $strapi.user:
![image](https://user-images.githubusercontent.com/56795373/92406800-9f89d500-f141-11ea-9bb2-661f53ed3b96.png)
U can see the structure that have user object.
Expected that after a page refresh, the user structure remains the same.

### What is actually happening?
After a page refresh i get this structure using $strapi.user:
![image](https://user-images.githubusercontent.com/56795373/92406868-ce07b000-f141-11ea-83cf-bf480fd7faf2.png)
As u can see, there are some missing properties.

I hope u can help me with this one.
Thank you in advance <3

**Comment by alfianriv** [comment]
I think there is something delete cookies jwt_strapi after page refreshed. For now as alternative you can store jwt by using `this.$strapi.$cookies.set('key', 'value')` with your custom key after get jwt in login. And setToken by getting it token from cookies in middleware.

**Comment by KevinNTH** [comment]
Using @nuxtjs/strapi: ^0.1.6, I also encounter this issue where $strapi.user `null` even `jwt_strapi` is set after page refreshed. I think Strapi Nuxt module is not loading the JWT token on page load.

**Comment by baermathias** [comment]
Same issue here

**Comment by benjamincanac** [comment]
Are you sure your login endpoint `POST /auth/local` and your user endpoint `GET /users/me` send back the exact same data? Those are two different controller in Strapi and relations may not be fetched in the same way.

**Comment by benjamincanac** [comment]
Maybe this was closed a bit early, I've just made a fix for apps in `ssr` true and target `static` in #68 and released in [v0.1.8](https://github.com/nuxt-community/strapi-module/releases/tag/v0.1.8).
