### ISSUE TITLE
E2E and unit tests 

### ISSUE THREAD

**Issue by myfailemtions** [nuxt-community/strapi-module#5]
### Is your feature request related to a problem? Please describe.
I believe that it is necessary to cover the available functionality with tests. Need to start by creating a Fixture and a standard e2e test and add unit tests.

### Describe the solution you'd like
I want to help with this task and start by writing a base for future tests

**Comment by Atinux** [comment]
Hi @myfailemtions 

The main issue here is that we cannot really do E2E without having a Strapi server running, and mocking it might by fastidious.

What can be done is Unit testing, you are more than welcome to add them, you can look at https://github.com/nuxt/http/blob/dev/test/with-config.test.js to inspire you.

Thank you so much for your help 💚
