### ISSUE TITLE
Cannot read property 'get' of undefined (cookie)

### ISSUE THREAD

**Issue by TonyDeplanque** [nuxt-community/strapi-module#60]
After installed your module, i had got a fatal error "**Cannot read property 'get' of undefined**" with getToken method in .nuxt/strapi.js line 148 on all pages.

` getToken () {
    return this.$cookies.get(TOKEN_KEY)
  }`

I don't understand why do you retrieve token in constructor because to register we don't need a jwt-token.

### Version
@nuxtjs/strapi: 0.1.7
nuxt: 2.14.6

**Comment by TonyDeplanque** [comment]
In fact, it don't found $cookies...

**Comment by T-Zahil** [comment]
You can use  `this.$strapi.$cookies` (https://strapi.nuxtjs.org/strapi#cookies)

**Comment by dimst** [comment]
Not fixed.

![Screenshot_1](https://user-images.githubusercontent.com/2500054/121181656-b057aa80-c87b-11eb-8f95-c3a0c479d8ef.png)

**Comment by gkkirilov** [comment]
@dimst  I had to change the order or the modules I was using, I put strapi first
