### ISSUE TITLE
Parameters documentation

### ISSUE THREAD

**Issue by DragonWhisperer** [nuxt-community/strapi-module#66]
The [`find(entity, params)`](https://strapi.nuxtjs.org/strapi/#findentity-params) only shows the basics.
How to use all the parameters [here](https://strapi.io/documentation/v3.x/content-api/parameters.html#parameters)? Can you provide more examples?

**Comment by Rendxn** [comment]
I would also like to know

**Comment by NooBiToo** [comment]
Я тоже хотел бы знать

**Comment by NooBiToo** [comment]
hi guys,
@DragonWhisperer , @Rendxn 
i'm used _sort param,
ex: articles: await $strapi.find("articles", { _sort: "created_at:desc" })
I think the other parameters are used the same way

**Comment by benjamincanac** [comment]
The Strapi module is a just a wrapper to call your API. Are you sure `GET /categories?_sort=articles.created_at:desc` works?

**Comment by Rendxn** [comment]
Actually, it works fine using the `$strapi.find('categories', { _sort: 'created_at:desc })` and the same applies for any other Strapi parameter (_limit, _sort, _start, etc)
If you wanna use categories, you should take a look at the [Strapi guide](https://strapi.io/documentation/v3.x/getting-started/quick-start.html#_4-create-a-category-content-type), where they use Restaurants and Categories, then when you fetch your articles you could do: `$strapi.find('articles', { category.name: yourCategoryName })`.
Also, if you are doing `$strapi.find('categories', { _sort: 'created_at:desc })`, this will get the articles related to each category with them unless you set them to [private](https://strapi.io/documentation/v3.x/concepts/models.html#define-the-attributes) in your model json.

**Comment by luixal** [comment]
I'm having a problem here when trying to use `_where`. As per the [docs here](https://strapi.io/documentation/v3.x/content-api/parameters.html#complex-queries), this should work:

```js
const query = qs.stringify({ _where: { _or: [{ stars: 1 }, { pricing_gt: 30 }] } });
await request(`/restaurant?${query}`);
```

I've tried this:

```js
params._where = {
  _or: [
    {name_contains: 'a'},
    {description_contains: 'a'},
    {serial_contains: 'a'}
  ]
}
```

and this:

```js
params._where = qs.stringify({
  _or: [
    {name_contains: 'a'},
    {description_contains: 'a'},
    {serial_contains: 'a'}
  ]
})
```

with no luck. I get a `404 Bad Request` error with the message: `HTTPError: Your filters contain a field '0' that doesn't appear on your model definition nor it's relations`. If I built the query manually, like this:

```js
params['_where[_or][0][name_contains]'] = 'a';
params['_where[_or][1][description_contains]'] = 'a';
params['_where[_or][2][serial_contains]'] = 'a';
```

It works. I guess there's some problem when building the url with complex params. Maybe the use of `qs.stringify` for the whole params object is needed, don't know.

Anyone has been lucky doing something like this?

Thanks!

**Comment by benjamincanac** [comment]
@luixal You don't need to use `qs.stringify` here, the module does it for you, check out the documentation [here](https://strapi.nuxtjs.org/usage).

```js
$strapi.find('restaurants', { _where: { _or: [{ stars: 1 }, { pricing_gt: 30 }] } })
```

**Comment by alexey13** [comment]
@benjamincanac 
On my end it not works. Can you please test it?
```
$strapi.find('restaurants', { _where: { _or: [{ stars: 1 }, { pricing_gt: 30 }] } })
error http://localhost:1337/restaurants?_where=%5Bobject+Object%5D
```

**Comment by alexey13** [comment]
Yeah, I use qs and it works nice!

**Comment by luixal** [comment]
I didn't get it working back in the day, anyway, we had to go other way that fit better our needs. I cannot test it right now but seeing @alexey13 confirmation I'll take it into consideration for next time :)

Thanks!

**Comment by mrsuarezg** [comment]
Por si ha alguien le sirve yo utilize qs, pero cometía el error de pasarlo:
const academy = await this.$strapi.find('collection-example', { queryCollection })
Cuando la forma correcta era usar el cliente http de Strapi puesto que el módulo de Nuxt no soporta nativamente la versión 4 aunque lo diga.
Lo siguiente funcionó para mi:
const results = await this.$strapi.$http.$get('collection-example', { searchParams: queryCollection })
