### ISSUE TITLE
Right way to set up STRAPI_URL in .env

### ISSUE THREAD

**Issue by baermathias** [nuxt-community/strapi-module#67]
How do I use STRAPI_URL ? I have tried the following:

File `.env`:
```javascript
STRAPI_URL="http://localhost:1337"
```
File `.env.production`:
```javascript
STRAPI_URL="https://my-app.herokuapp.com/"
```
In `nuxt.config.js` I have first tried to set env property and the new runtime config:
```javascript
env: {
  STRAPI_URL: process.env.STRAPI_URL || 'http://localhost:1337',
},

publicRuntimeConfig: {
  STRAPI_URL: process.env.STRAPI_URL,
},
```
Then I have also tried the url option:
```javascript
strapi: {
  url: process.env.STRAPI_URL || 'http://localhost:1337',
},
```
It doesn't work, `$strapi` is always doing calls to localhost:1337.

**Comment by benjamincanac** [comment]
@baermathias You can just set `STRAPI_URL=https://my-app.herokuapp.com` in your `.env` file and it should work.

**Comment by baermathias** [comment]
In my `.env.production` ? Or how would I specify which url is loaded into the prod environment?

**Comment by Atinux** [comment]
Nuxt does not support `.env.production` @baermathias 

You need to directly add it to `.env` or in your hosting provider.

**Comment by luixal** [comment]
I think I needed to put

```js
require("dotenv").config();
```

on top of `nuxt.config.js`. Then, referenced the URL like this (in this case for the auth module):

```js
`${process.env.API_AUTH_URL}/auth/local`
```

**Comment by baermathias** [comment]
@Atinux Thank you for the answer, but if I add my constants directly to `.env`, how do I specify different values for different environments in this one file?? My solution is now to use a js file instead of `.env`:

```javascript
// env.config.js - all the env constants with their different values (depending on the env) 

const configs = {
  development: {
    BASE_URL: "http://localhost:1337",
    STRAPI_URL: "http://localhost:1337",
    MEDIA_CDN: "http://localhost:1337"
  },
  staging: {
    BASE_URL: "https://....herokuapp.com",
    STRAPI_URL: "https://....herokuapp.com",
    MEDIA_CDN: "https://....s3.eu-central-1.amazonaws.com"
  },
  production: {
    BASE_URL: "https://....herokuapp.com",
    STRAPI_URL: "https://....herokuapp.com",
    MEDIA_CDN: "https://....s3.eu-central-1.amazonaws.com"
  }
}

const nodeEnv = process.env.NODE_ENV
module.exports = configs[nodeEnv]
```

```javascript
// nuxt.config.js - now you can use all the constants (with the considered env) in different places

const {BASE_URL, STRAPI_URL, MEDIA_CDN} = require('./env.config')

export default {
  env: {
    BASE_URL,
    MEDIA_CDN
  },
  publicRuntimeConfig: {
    BASE_URL,
    MEDIA_CDN
  },
  privateRuntimeConfig: {
    // ...
  },
  strapi: {
    url: STRAPI_URL
  },

**Comment by Atinux** [comment]
@luixal you don't need to require('dotenv'), Nuxt does it for you.

@baermathias This is a valid solution, keep in my mind that you may expose sensitive information to git if this file is not gitignore

**Comment by luixal** [comment]
@Atinux right, it isn't need. I would assure I had to add it once, but I can confirm it's working without :)
