### ISSUE TITLE
ERROR undefined on nodejs 14.15

### ISSUE THREAD

**Issue by NooBiToo** [nuxt-community/strapi-module#73]
Help pls
After updating the node from 12.x to 14.15, I cannot start the project, I tried to deploy a new project from the github, but I get the same error

 ```
ERROR  undefined                                                                                                                                                                       17:26:14  

  at fn (node_modules/ky/umd.js:321:0)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async Ky._retry (node_modules/ky/umd.js:412:0)
  at async HTTP.module.exports../.nuxt/http.js.HTTP.<computed> [as get] (.nuxt/http.js:92:0)
  at async asyncData (index.vue:24:0)
```
Index.vue 24 code:
```
async asyncData({ $strapi }) {
    return {
      articles: await $strapi.find("articles", { _sort: "created_at:desc" }),
      homepage: await $strapi.find("homepage"),
      categories: await $strapi.find("categories"),
      global: await $strapi.find("global"),
    };
  },
```

**Comment by adhamfarrag** [comment]
+1 but my error is Forbidden not Undefined even when I do login and registration normally. 
@NooBiToo Did you come to any solution around it? 

 ERROR  Forbidden                                                                                                                              10:39:09

  at fn (node_modules/ky/umd.js:323:0)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async Ky._retry (node_modules/ky/umd.js:418:0)
  at async HTTP.module.exports../.nuxt/http.js.HTTP.<computed> [as get] (.nuxt/http.js:92:0)
  at async asyncData (pages/index.vue:25:0)

**Comment by NooBiToo** [comment]
> +1 but my error is Forbidden not Undefined even when I do login and registration normally.
> @NooBiToo Did you come to any solution around it?
> 
> ERROR Forbidden 10:39:09
> 
> at fn (node_modules/ky/umd.js:323:0)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> at async Ky._retry (node_modules/ky/umd.js:418:0)
> at async HTTP.module.exports../.nuxt/http.js.HTTP. [as get] (.nuxt/http.js:92:0)
> at async asyncData (pages/index.vue:25:0)

Hello!
I managed to understand why this is happening.
I had a stupid mistake, my hoster restored the Strapy backup, where the **global** and **homepage** collections were missing

**Comment by adhamfarrag** [comment]
I did more stupid one by not checking weather roles has access or not..
